name: LobbyCore
main: Afq\LobbyCore\Main
api: [4.0.0]
version: 1.0.0
author: Afq

commands:
  hub:
    description: "Teleport back to hub"
    permission: lobbycore.hub.cmd
  lobby:
    description: "Teleport back to lobby"
    permission: lobbycore.lobby.cmd
  spawn:
    description: "Teleport back to spawn"
    permission: lobbycore.spawn.cmd

permissions:
  lobbycore.hub.cmd:
    default: true
  lobbycore.lobby.cmd:
    default: true
  lobbycore.spawn.cmd:
    default: true
